services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - WEBHOOK_TUNNEL_URL=http://0.0.0.0:5678
      - N8N_CORS_ALLOW_ORIGIN=*
      - N8N_CORS_ALLOW_METHODS=GET,POST,OPTIONS
      - N8N_CORS_ALLOW_HEADERS=Content-Type,Authorization
    volumes:
      - ~/.n8n:/home/node/.n8n
    restart: unless-stopped
